# Generated by Django 5.1.6 on 2025-04-24 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='template',
            name='file',
        ),
        migrations.AddField(
            model_name='template',
            name='additional_images',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='template',
            name='customizations',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='template',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='templates.template')),
            ],
        ),
    ]
