# Generated by Django 5.1.6 on 2025-04-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_remove_template_created_at_remove_template_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='customizations',
        ),
        migrations.AddField(
            model_name='template',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='template',
            name='tech_stack',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
