# Generated by Django 5.1.6 on 2025-04-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_remove_template_customizations_template_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='live_preview_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
