# Generated by Django 5.1.6 on 2025-04-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='zip_file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
