# Generated by Django 5.1.6 on 2025-05-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0006_template_zip_file_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('inquiry_type', models.CharField(choices=[('PAYMENT_FAILURE', 'Payment Failure'), ('PAYMENT_STATUS', 'Payment Status'), ('TEMPLATE_DOWNLOAD', 'Template Download Issue'), ('GENERAL', 'General')], max_length=20)),
                ('description', models.TextField()),
                ('order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
