# Generated by Django 5.2.1 on 2025-05-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0007_supportinquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
